spring.datasource.url: jdbc:h2:file:./camunda-h2-database
server.port: 8001

camunda.bpm:
  admin-user:
    id: demo
    password: demo
    firstName: Demo
  filter:
    create: All tasks
    
    
camunda.bpm.client:
  base-url: http://localhost:8001/engine-rest # the URL pointing to the Camunda Platform Runtime REST API
  lock-duration: 10000 # defines how many milliseconds the External Tasks are locked until they can be fetched again

logging.level.org.camunda.bpm.client: INFO # increase the log level of the application

#vCloud vCenter simulator
vmware.vcenter.host: http://vcloud.wiremockapi.cloud
#GET
vmware.vcenter.folder.api: /api/vcenter/folder
vmware.vcenter.cluster.api: /api/vcenter/cluster/cluster-clientes
vmware.vcenter.datastore.api: /api/vcenter/datastore/{variable}
vmware.vcenter.datastore.all.api: /api/vcenter/datastore
vmware.vcenter.resource-pool.all.api: /api/vcenter/resource-pool
vmware.vcenter.resource-pool.api: /api/vcenter/resource-pool/{variable}
#POST
vmware.vcenter.host.api: /api/vcenter/host
vmware.vcenter.vm.api: /api/vcenter/vm
vmware.vcenter.vm.relocate.api: /api/vcenter/vm/{variable}?action=relocate

#HOST
vmware.host.hostname: domain.cluster-clientes
vmware.host.username: username
wmware.host.password: password
